config/routes.rb
Rails.application.routes.draw do

  get "get_user_id" => 'sessions#get_user_id', :as => "get_user_id"
  resources :sessions, only: [:create, :destroy]
  resources :decks, only: [:index]
  resources :photos, only: [:show, :create]

  resources :users, only:[:create, :show] do
    resources :rounds, only: [:index]
  end

  resources :rounds, only: [:create] do
    resources :photos, only: [:index]
  end

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :prompts

  def self.formatted
    Deck.all.map { |deck| { id: deck.id, name: deck.name } }
  end

  def self.random_prompt(deck_id)
    Deck.find(deck_id).prompts.sample.id
  end

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  validates :round_id, presence: true
  validates :phone, :email, uniqueness: true

  has_many :round_invites
  has_many :rounds, through: :round_invites
end

app/models/participant_round.rb
class ParticipantRound < ActiveRecord::Base
  validates :round_id, :participant_id, presence: true

  belongs_to :round
  belongs_to :participant, class_name: "User"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :round_id, :user_id, :prompt_id, presence: true

  mount_uploader :image, ImageUploader

  belongs_to :round
  belongs_to :user
  belongs_to :prompt

end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
  validates :deck_id, :body, presence: true
  validates :body, uniqueness: true

  has_many :rounds
  has_many :photos
  belongs_to :deck
end

app/models/round.rb
class Round < ActiveRecord::Base
  validates :creator_id, :prompt_id, :end_time, presence: true

  has_many :round_invites
  has_many :invites, through: :round_invites
  has_many :photos
  has_many :participant_rounds
  has_many :participants, through: :participant_rounds, class_name: "User", foreign_key: :participant_id
  belongs_to :creator, class_name: "User", foreign_key: :creator_id
  belongs_to :prompt

  def has_photos?(user_id)
    self.photos.any?{ |photo| photo.user_id == user_id}
  end

  def attr_hash
    { round_id: self.id,
      creator_id: self.creator_id,
      creator_first_name: self.creator.first_name,
      prompt: self.prompt.body,
      end_time: self.end_time }
  end

  def add_participants(contact_numbers)
    self.participants = contact_numbers.map{ |phone_number| User.find_by(phone: phone_number) } if contact_numbers
    self.participants << User.find(self.creator_id)
  end

  def self.hash_collection(rounds_array)
    rounds_array.map { |round| round.attr_hash }
  end

  def submitted_participants
    self.participants.select { |participant| participant.photos.find_by(round_id: self.id) }
  end

  def pending_participants
    self.participants.select { |participant| !participant.photos.find_by(round_id: self.id) }
  end

  def submitted_participants_formatted
    self.submitted_participants.map { |user| { first_name: user.first_name,
      photo: user.photos.find_by(round_id: self.id).image_url.to_s } }
  end

  def pending_participants_formatted
    self.pending_participants.map{|user| { first_name: user.first_name } }
  end

end

app/models/round_invite.rb
class RoundInvite < ActiveRecord::Base
  validates :round_id, :invite_id, presence: true

  belongs_to :round
  belongs_to :invite
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :first_name, :last_name, :email, :phone, :password, presence: true
  validates :email, :phone, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_format_of :phone, :with => /^\d{10}$/, multiline: true

  has_many :participant_rounds, foreign_key: :participant_id
  has_many :rounds, through: :participant_rounds
  has_many :photos

  def open_rounds
    self.rounds.where("end_time > ?", DateTime.now)
  end

  def closed_rounds
    self.rounds.where("end_time < ?", DateTime.now).reverse
  end

  def pending_rounds
    self.open_rounds.find_all { |round| !round.has_photos?(self.id)}.reverse
  end

  def submitted_rounds
    self.open_rounds.find_all { |round| round.has_photos?(self.id)}.reverse
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

  def index
    render :json => { decks: Deck.formatted }
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    round = Round.find_by(id: params[:round_id])
    render :json => {
      participants: {
        submitted: round.submitted_participants_formatted,
        pending: round.pending_participants_formatted
      }
    }
  end

  def show
    photo = Photo.find_by(id: params[:id])
    render :json => {
      photo: {
        user_id: photo.user.id,
        first_name: photo.user.first_name,
        prompt: photo.prompt.body,
        url: photo.image_url
      }
    }
  end

  def create
    round = Round.find_by(id: params[:round_id])
    photo = Photo.new(image: params[:image], round_id: round.id, user_id: params[:user_id], prompt_id: round.prompt.id)
    if photo.save
      render :json => { photo_id: photo.id }
    else
      render :status => :not_modified
    end
  end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  def index
    user = User.find_by(id: params[:user_id])
    render :json => {
      pending_rounds: Round.hash_collection(user.pending_rounds),
      submitted_rounds: Round.hash_collection(user.submitted_rounds)
    }
  end

  def create
    round = Round.new(creator_id: params[:id], prompt_id: Deck.random_prompt(params[:deck_id]), end_time: DateTime.now + 1.days)
    if round.save
      round.add_participants(params[:contact_numbers])
      render :json => { round: round.attr_hash }
    else
      render :status => :not_modified
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def get_user_id
    render :json => { id: session[:user_id], first_name: User.find(session[:user_id]).first_name }
  end

  def destroy
    session.clear
    render :json => { status: "Session has been cleared."}
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      render :json => { id: @user.id }
    else
      render :status => :forbidden, :text => "Login failed"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], phone: params[:phone], password: params[:password])
    if user.save
      session[:user_id] = user.id
      render :json => { user_id: user.id }
    else
      render :status => :not_modified
    end
  end

  def show
    user = User.find_by(id: params[:id])
    render :json => { rounds: Round.hash_collection(user.closed_rounds) }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/decks/index.html.erb
<%= link_to "Back", user_rounds_path(@user) %>
<div class="deck-list-header">Choose a Deck:</div>
<ul class="deck-list">
  <% @decks.each do |deck| %>
  <li>
    <%= link_to "#{deck.name}", prompt_contacts_path(@prompt)%>
  </li>

  <% end %>
</ul>

app/views/decks/index1.html.erb
<%= link_to "Back", user_rounds_path(@user) %>
<div class="deck-list-header">Choose a Deck:</div>
<ul class="deck-list">
  <% @decks.each do |deck| %>
  <li>
    <%= link_to "#{deck.name}", prompt_contacts_path(@prompt)%>
  </li>

  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picture This</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picture This</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<div class="photo-list-header">Round Photos:</div>
Submitted:<br>
<ul>
  <!-- Remove this example link -->
  <!-- <li> %#link_to "Photo Link", round_photo_path(@round, @photo)% </li> -->
<% @photos.each do |photo| %>
  <li>
  <%= photo.user.first_name %>
  <%= link_to "Photo Show", round_photo_path(@round, photo) %>
  </li>
<% end %>
</ul>
Invited:<br>
<%= link_to "Open Rounds", user_rounds_path(@user) %>
<%= link_to "Closed Rounds", user_path(@user) %>

app/views/photos/index1.html.erb
<div class="photo-list-header">Round Photos:</div>
Submitted:<br>
<ul>
  <!-- Remove this example link -->
  <!-- <li> %#link_to "Photo Link", round_photo_path(@round, @photo)% </li> -->
<% @photos.each do |photo| %>
  <li>
  <%= photo.user.first_name %>
  <%= link_to "Photo Show", round_photo_path(@round, photo) %>
  </li>
<% end %>
</ul>
Invited:<br>
<%= link_to "Open Rounds", user_rounds_path(@user) %>
<%= link_to "Closed Rounds", user_path(@user) %>

app/views/photos/show.html.erb
<li><%= link_to "Back to Gallery", round_photos_path(@round) %></li>
<%= @photo.user.first_name %>'s Photo<br>
<%= image_tag @photo.image_url.to_s %>
Find Something:<br>
<%= @photo.prompt.body %>

app/views/photos/show1.html.erb
<li><%= link_to "Back to Gallery", round_photos_path(@round) %></li>
<%= @photo.user.first_name %>'s Photo<br>
<%= image_tag @photo.image_url.to_s %>
Find Something:<br>
<%= @photo.prompt.body %>

app/views/rounds/index1.html.erb
<div class="logo">Picture This</div>
<div class="list-header">Open Rounds</div>
<ul class="list-rounds">
  <% @rounds.each do |round| %>
    <li class="round">
      <%= round.creator.first_name %>
      <%= link_to "Prompt", round_path(round) %>
      <%= round.id %>
    </li>
  <% end %>
</ul>
<%= link_to "Closed Rounds", user_path(@user) %>
<%= link_to "New Round", user_decks_path(@user) %>

app/views/rounds/show.html.erb
<div class="prompt-intro">Find Something:</div>
<%= @prompt.body %><br>
<%= @round.end_time %><br>
<!-- <button type="button" name="button">Camera</button><br> -->
<!-- Submitted:<br> -->

<%= form_tag round_photos_path(@round.id), :enctype => 'multipart/form-data' do %>
  <%= file_field_tag :image %>
  <%= hidden_field_tag 'prompt_id', "#{@prompt.id}" %>
  <%= hidden_field_tag 'user_id', "#{@user.id}" %>
  <%= submit_tag "Post that shizz" %>
<% end %>

<%= link_to "Open Rounds", user_rounds_path(@user) %>
<%= link_to "Closed Rounds", user_path(@user) %>

app/views/rounds/show1.html.erb
<div class="prompt-intro">Find Something:</div>
<%= @prompt.body %><br>
<%= @round.end_time %><br>
<!-- <button type="button" name="button">Camera</button><br> -->
<!-- Submitted:<br> -->

<%= form_tag round_photos_path(@round.id), :enctype => 'multipart/form-data' do %>
  <%= file_field_tag :image %>
  <%= hidden_field_tag 'prompt_id', "#{@prompt.id}" %>
  <%= hidden_field_tag 'user_id', "#{@user.id}" %>
  <%= submit_tag "Post that shizz" %>
<% end %>

<%= link_to "Open Rounds", user_rounds_path(@user) %>
<%= link_to "Closed Rounds", user_path(@user) %>

app/views/users/new.html.erb
<div class="logo">Picture This</div>
<% if @errors %>
	<ul class="errors">
  <% @errors.each do |error| %>
    <li><%= error %></li>
  <% end %>
	</ul>
<% end %>
<div class="login-form">
	<%= form_for @user do |f| %>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %><br>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %><br>
    <%= f.label :email %><br>
	  <%= f.text_field :email %><br>
    <%= f.label :phone %><br>
	  <%= f.text_field :phone %><br>
	  <%= f.label :password %><br>
	  <%= f.password_field :password %><br>
	  <%= f.submit "Register" %>
 	<% end %>
</div>
<div>
<%= link_to "Login", login_path %>
</div>

app/views/users/new1.html.erb
<div class="logo">Picture This</div>
<% if @errors %>
	<ul class="errors">
  <% @errors.each do |error| %>
    <li><%= error %></li>
  <% end %>
	</ul>
<% end %>
<div class="login-form">
	<%= form_for @user do |f| %>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %><br>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %><br>
    <%= f.label :email %><br>
	  <%= f.text_field :email %><br>
    <%= f.label :phone %><br>
	  <%= f.text_field :phone %><br>
	  <%= f.label :password %><br>
	  <%= f.password_field :password %><br>
	  <%= f.submit "Register" %>
 	<% end %>
</div>
<div>
<%= link_to "Login", login_path %>
</div>

app/views/users/show.html.erb
<%= link_to "Logout", logout_path %>
<div class="logo">Picture This</div>
<div class="list-header">Closed Rounds</div>
<ul class="list-rounds">
  <% @rounds.each do |round| %>
    <li class="round">
      <%= round.creator.first_name %>
      <%= link_to "Gallery", round_photos_path(round) %>
      <%= round.id %>
    </li>
  <% end %>
</ul>
<%= link_to "Open Rounds", user_rounds_path(@user) %>
<%= link_to "New Round", user_decks_path(@user) %>

app/views/users/show1.html.erb
<%= link_to "Logout", logout_path %>
<div class="logo">Picture This</div>
<div class="list-header">Closed Rounds</div>
<ul class="list-rounds">
  <% @rounds.each do |round| %>
    <li class="round">
      <%= round.creator.first_name %>
      <%= link_to "Gallery", round_photos_path(round) %>
      <%= round.id %>
    </li>
  <% end %>
</ul>
<%= link_to "Open Rounds", user_rounds_path(@user) %>
<%= link_to "New Round", user_decks_path(@user) %>